import './globals.css'

export const metadata = {
  title: 'Portfolio Page',
  description: 'Generated by Tanner90909',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>{children}</body>
    </html>
  )
}
